# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98fe393fcd532cdf442e2da1cde6eed80fd459fef6debb2ec4ee6106e55d8060775eb818975612ed34c56242c2a9ad24679e486ff62508c9af6cf5561d64f6bb

test:
  secret_key_base: f84cb1ec198a60a243b3d5f46efbd6a0880c29d929dc60c2a815e480c95596c19a21b3fd7267ba7bd5fba332ef9e899d51837fa26fc859b60a971a1550231c94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
